six-goguma/Algo-Hive-BE

build.gradle
src/main/java/com/knu/algo_hive/common/config/SwaggerConfig.java
src/main/java/com/knu/algo_hive/common/controller/testController.java
src/main/resources/application.properties

- #2 
- h2 db 활성화
- swagger 활성화
- nginx 웹서버 조정
없습니다.
> close #2

Feat: 도메인 h2-console, swagger-ui 경로 처리

---

.github/workflows/docker-push-deploy.yml

- #11 
- 깃액션 빌드과정에서 gemini api key 환경변수로 추가
배포과정에서 확인 가능합니다.
close #11

HotFix: 깃액션 빌드과정에서 gemini api key 환경변수로 추가

---

.github/workflows/docker-push-deploy.yml
k8s/deployment.yaml.template

- #24 
- 도커에 환경변수 추가
- 깃액션에 환경변수 추가
- 깃 시크릿에 환경변수 추가
- 쿠버네티스 deployment 파일에 환경변수 추가
- vm 서버 내부 db.secret파일에 환경변수 추가
없습니다.
close #24

Deploy: 도훈 작업물(세션 회원)에 서버 환경변수 작업

---

src/main/java/com/knu/algo_hive/post/controller/PostController.java
src/main/java/com/knu/algo_hive/post/entity/Post.java
src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
src/main/java/com/knu/algo_hive/post/service/PostService.java

- 태그 관련 코드때문에 배포에 실패해서 주석화 시켰습니다!
>
> close #이슈번호
>

Fix: 아직 미완성인 태그 관련 코드 주석화

---

src/main/java/com/knu/algo_hive/post/controller/PostController.java
src/main/java/com/knu/algo_hive/post/controller/TagController.java
src/main/java/com/knu/algo_hive/post/dto/TagRequest.java
src/main/java/com/knu/algo_hive/post/dto/TagResponse.java
src/main/java/com/knu/algo_hive/post/entity/PostTag.java
src/main/java/com/knu/algo_hive/post/entity/PostTagId.java
src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
src/main/java/com/knu/algo_hive/post/repository/PostTagRepository.java
src/main/java/com/knu/algo_hive/post/service/PostService.java
src/main/java/com/knu/algo_hive/post/service/TagService.java

#38 
- 태그기능 구현을 완료하였습니다.
- `@IdClass` 를 활용해서 복합키로 한번 관리하게 해보았습니다. equals, hashCode를 직접 오버라이딩 가능한점이 좋았던거 같습니다.
- 태그는 id를 백엔드에서 주고 해당 id 의 명칭은 프론트가 알아서 정하는식으로 생각하고 구현해보았습니다!
>
> close #이슈번호
> 
close #38

Feat: 태그 기능 구현

---

Dockerfile

- #45 
- 도커파일 수정으로 컨테이너 시간동기화
- 도커파일 수정으로 실행환경 시간동기화
서버 업로드 과정에서 확인 가능
close #45

Deploy: 컨테이너 및 스프링어플리케이션 실행 환경 시간 서울로 동기화

---

src/main/java/com/knu/algo_hive/post/entity/Post.java

- TODO
- TODO
>
> close #이슈번호
>

fix:  `@Version` 구현 패키지 변경

---

src/main/java/com/knu/algo_hive/common/exception/ErrorCode.java
src/main/java/com/knu/algo_hive/post/controller/CommentController.java
src/main/java/com/knu/algo_hive/post/controller/LikeController.java
src/main/java/com/knu/algo_hive/post/controller/PostController.java
src/main/java/com/knu/algo_hive/post/controller/TagController.java
src/main/java/com/knu/algo_hive/post/entity/Comment.java
src/main/java/com/knu/algo_hive/post/entity/Post.java
src/main/java/com/knu/algo_hive/post/repository/CommentRepository.java
src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
src/main/java/com/knu/algo_hive/post/service/CommentService.java
src/main/java/com/knu/algo_hive/post/service/LikeService.java
src/main/java/com/knu/algo_hive/post/service/PostService.java
src/main/java/com/knu/algo_hive/post/service/TagService.java

#40 
- 댓글 기능 완료하였습니다. 좀 더 추가할 기능이 있으려나요? 감사합니다!😊
- 단순한 스웨거 에러코드 지정하는거랑, ErrorCode 메시지 추가하는것도 반영하겠습니다!
>
> close #이슈번호
> 
close #40

Feat: 댓글 기능 구현

---

src/main/java/com/knu/algo_hive/auth/controller/MyPageController.java
src/main/java/com/knu/algo_hive/auth/dto/ProfileRequest.java
src/main/java/com/knu/algo_hive/auth/dto/ProfileResponse.java
src/main/java/com/knu/algo_hive/auth/entity/Member.java
src/main/java/com/knu/algo_hive/auth/entity/Profile.java
src/main/java/com/knu/algo_hive/auth/repository/ProfileRepository.java
src/main/java/com/knu/algo_hive/auth/service/MyPageService.java
src/main/java/com/knu/algo_hive/common/config/WebConfig.java
src/main/java/com/knu/algo_hive/common/exception/ErrorCode.java
src/main/resources/application.properties

> ex) #52 
- 프로필 사진 추가 / 조회 / 삭제 기능 구현
- 로그아웃 기능 구현
- 회원탈퇴 기능 구현
- 닉네임 변경 기능 구현
- Swagger에 api 문서 반영
> 환경설정 제대로 됬는지 확인해야되서 후딱 머지하고 테스트해보겟습니다...
> close #이슈번호
>

Feat : 마이페이지 기능 구현

---

.github/workflows/docker-push-deploy.yml
k8s/deployment.yaml.template
src/main/java/com/knu/algo_hive/common/exception/ErrorCode.java

> ex) #52 
- ErrorCode 파일 날라간 부분 반영
- deploy 파일 변경
- k8s 파일 변경
>
> close #이슈번호
>

Fix, Deploy : ErrorCode 파일 수정 및 배포 설정 변경

---

src/main/java/com/knu/algo_hive/common/config/WebConfig.java

> ex) #52
- allowCredentials(true)로 변경 => 쿠키 및 세션 정보 전달 받음
>
> close #이슈번호
>

HotFix : Credentials허용

---

build.gradle
src/main/java/com/knu/algo_hive/auth/entity/Member.java
src/main/resources/application.properties

> ex) #52
- 레디스 연동 3트째...
>
> close #이슈번호
>

bugfix : 레디스 연동

---

src/main/java/com/knu/algo_hive/common/config/WebConfig.java

> ex) #52
- 이미지 로딩 문제 해결 시도(1)
>
> close #이슈번호
>

refactor : 오탈자 수정

---

src/main/java/com/knu/algo_hive/chat/controller/ChatController.java
src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java
src/main/java/com/knu/algo_hive/chat/service/RoomService.java

- #60 
- 채팅방 페이지네이션 처리
- 채팅 불러오기 페이지네이션 처리
- 프론트 무한스크롤 및 페이지네이션 적용 테스트
서버 업로드 후 확인 가능합니다.
close #60

Refactor: 채팅방 및 채팅 불러오기 페이지네이션 처리

---

src/main/java/com/knu/algo_hive/common/config/WebConfig.java
src/main/java/com/knu/algo_hive/post/controller/CommentController.java
src/main/java/com/knu/algo_hive/post/controller/ImageController.java
src/main/java/com/knu/algo_hive/post/controller/LikeController.java
src/main/java/com/knu/algo_hive/post/controller/PostController.java
src/main/java/com/knu/algo_hive/post/controller/TagController.java
src/main/java/com/knu/algo_hive/post/dto/CommentRequest.java
src/main/java/com/knu/algo_hive/post/dto/CommentResponse.java
src/main/java/com/knu/algo_hive/post/dto/ImageDeleteRequest.java
src/main/java/com/knu/algo_hive/post/dto/ImageUploadRequest.java
src/main/java/com/knu/algo_hive/post/dto/PostRequest.java
src/main/java/com/knu/algo_hive/post/dto/PostResponse.java
src/main/java/com/knu/algo_hive/post/dto/UrlResponse.java
src/main/java/com/knu/algo_hive/post/service/CommentService.java
src/main/java/com/knu/algo_hive/post/service/ImageService.java
src/main/java/com/knu/algo_hive/post/service/PostService.java
src/main/resources/application.properties

#62 
- 이미지 관련 기능 구현
- 명칭 수정
- 로컬에서 파일 업로드/조회/제거 잘 되는거확인했습니다!
>
> close #이슈번호
> 
close #62

Feat: 이미지 관련 기능 구현

---

src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
src/main/java/com/knu/algo_hive/common/config/AsyncConfig.java

- maxPoolsize 줄여서 시도해보겠습니다...ㅜㅜ
>
> close #이슈번호
>

hotfix: cpu 코어 문제 해결

---

src/main/java/com/knu/algo_hive/common/config/AsyncConfig.java

- cpu 두배로 늘려줘...
- TODO
>
> close #이슈번호
>

hotfix : corepool 2에서 1로 변경

---

src/main/resources/application.properties

> 세션 만료시간 적용되는 속성 코드 변경
- TODO
- TODO
>
> close #이슈번호
>

refactor : 세션 만료시간 지정

---

src/main/java/com/knu/algo_hive/AlgoHiveApplication.java
src/main/java/com/knu/algo_hive/auth/service/MemberService.java
src/main/java/com/knu/algo_hive/common/config/AsyncConfig.java

- TODO
- TODO
>
> close #이슈번호
>

bugfix : asnyc 변경

---

src/main/java/com/knu/algo_hive/auth/service/MemberService.java

- TODO
- TODO
>
> close #이슈번호
>

refactor : async 제거

---

k8s/deployment.yaml.template

- TODO
- TODO
>
> close #이슈번호
>

deploy : request cpu 변경

---

src/main/java/com/knu/algo_hive/auth/service/MyPageService.java
src/main/java/com/knu/algo_hive/chat/dto/ChatMessageInfo.java
src/main/java/com/knu/algo_hive/chat/dto/ChatMessageRequest.java
src/main/java/com/knu/algo_hive/chat/entity/ChatMessage.java
src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java

- #68 
- 채팅기능에 Member email을 연동
- 채팅 본인 식별 방식을 전환
- 프론트 코드 테스트
로컬에서는 없습니다.
close #68

Feat: 채팅 Member연동 및 본인 식별 방식 전환

---

src/main/java/com/knu/algo_hive/post/controller/PostController.java
src/main/java/com/knu/algo_hive/post/dto/PostIdResponse.java
src/main/java/com/knu/algo_hive/post/service/PostService.java

- TODO
- TODO
>
> close #이슈번호
>

Feat: 게시글 저장 성공 시 id 반환

---

src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
src/main/resources/application.properties

- TODO
- TODO
>
> close #이슈번호
>

Chore: 쿠키 설정

---

src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java

- TODO
- TODO
>
> close #이슈번호
>

Chore: 쿠키 default 설정으로 원상복귀

---

build.gradle
src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
src/main/java/com/knu/algo_hive/auth/service/MemberService.java
src/main/java/com/knu/algo_hive/common/config/RedisConfig.java
src/main/java/com/knu/algo_hive/common/properties/RedisProperties.java

> ex) #59 
- 리다이렉트 관련 로직 때문에 배포 시 문제가 생겨 이 부분은 제외하였습니다.
- 제거했던 분산 락 기능을 다시 추가하였고, spring security의 경로를 다시 활성화하였습니다.
>
> close #이슈번호
>

feat, refactor : 분산락 기능 다시 추가, spring security 경로 지정

---

src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java

> ex) #59 
- spring security 경로만 원래대로 하고 머지해보겠습니다.
>
> close #이슈번호
>

refactor : spring security 경로 원래대로

---

src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java

> ex) #59 
- 이미지 파일 경로도 추가했습니다!
>
> close #이슈번호
>

refactor : 이미지 관련 경로도 추가

---

src/main/java/com/knu/algo_hive/auth/config/CustomAuthenticationEntryPoint.java

> ex) #59
- 리다이렉트 로직이 이상하게 작동하여 일단 제거하겠습니다.
>
> close #이슈번호
>

bugfix: 리다이렉트 요청 제거
